// MIT License

#include <gtest/gtest.h>

#include <chrono>
#include <cstdlib>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <future>
#include <iostream>
#include <limits>
#include <memory>
#include <sstream>
#include <string>
#include <string_view>
#include <vector>

#include "algorithm/algorithm_description.h"
#include "base/party.h"
#include "communication/communication_layer.h"
#include "communication/tcp_transport.h"
#include "communication/transport.h"
#include "protocols/share_wrapper.h"
#include "test_constants.h"
#include "utility/bit_vector.h"

namespace {

using encrypto::motion::BitVector;

constexpr auto kProtocol = encrypto::motion::MpcProtocol::kBooleanGmw;

enum class BenchmarkTransport { kDummy, kTcp };

struct PrimitiveGateCase {
  std::string_view name;
  char aby_tag;
  std::vector<bool> inputs;
  bool expected_output;
};

struct PrimitiveGateBenchmarkResult {
  double parse_ms{0.0};
  double construct_ms{0.0};
  double run_ms{0.0};
  double total_ms{0.0};
  std::size_t messages_sent{0};
  std::size_t messages_received{0};
  std::size_t bytes_sent{0};
  std::size_t bytes_received{0};
};

double ToMilliseconds(std::chrono::steady_clock::duration duration) {
  return std::chrono::duration<double, std::milli>(duration).count();
}

std::size_t GetEnvSizeT(const char* name, std::size_t default_value) {
  if (const char* env = std::getenv(name); env != nullptr && *env != '\0') {
    const auto value = static_cast<std::size_t>(std::stoull(env, nullptr, 10));
    if (value == 0u) {
      throw std::invalid_argument(std::string(name) + " must be >= 1");
    }
    return value;
  }
  return default_value;
}

std::vector<BitVector<>> ToSingleBitInputs(const std::vector<bool>& inputs) {
  std::vector<BitVector<>> result;
  result.reserve(inputs.size());
  for (const auto value : inputs) {
    result.emplace_back(1, value);
  }
  return result;
}

std::filesystem::path WritePrimitiveGateCircuit(const PrimitiveGateCase& gate_case,
                                                std::size_t gate_count) {
  const auto unique_suffix = std::chrono::steady_clock::now().time_since_epoch().count();
  auto path = std::filesystem::temp_directory_path() /
              ("motion_fromaby_primitive_" + std::string(gate_case.name) + "_" +
               std::to_string(unique_suffix) + ".aby");

  std::ofstream stream(path);
  if (!stream.is_open()) {
    throw std::runtime_error("failed to create temporary ABY primitive benchmark circuit");
  }

  stream << "# Generated by FromAby primitive gate performance test\n";
  stream << "# Gate: " << gate_case.name << ", count: " << gate_count << "\n";
  stream << "#Inputs Alice (Server)\n";
  stream << "S";
  for (std::size_t input_i = 0; input_i < gate_case.inputs.size(); ++input_i) {
    stream << ' ' << input_i;
  }
  stream << "\n\n#Inputs Bob (Client)\nC\n\n#Gates\n";

  std::vector<std::size_t> output_wires;
  output_wires.reserve(gate_count);
  auto next_wire = gate_case.inputs.size();
  for (std::size_t gate_i = 0; gate_i < gate_count; ++gate_i) {
    const auto output_wire = next_wire++;
    output_wires.push_back(output_wire);
    switch (gate_case.aby_tag) {
      case 'X':
      case 'A':
      case 'V':
        stream << gate_case.aby_tag << '\t' << 0 << '\t' << 1 << '\t' << output_wire << '\n';
        break;
      case 'I':
        stream << gate_case.aby_tag << '\t' << 0 << '\t' << output_wire << '\n';
        break;
      case 'M':
        stream << gate_case.aby_tag << '\t' << 0 << '\t' << 1 << '\t' << 2 << '\t'
               << output_wire << '\n';
        break;
      default:
        throw std::invalid_argument("unsupported ABY primitive gate tag");
    }
  }

  stream << "\n#Outputs\nO";
  for (const auto output_wire : output_wires) {
    stream << ' ' << output_wire;
  }
  stream << '\n';
  return path;
}

std::vector<std::unique_ptr<encrypto::motion::Party>> MakeTcpConnectedParties(
    std::size_t number_of_parties, std::uint16_t base_port) {
  encrypto::motion::communication::TcpPartiesConfiguration configuration;
  configuration.reserve(number_of_parties);
  for (std::size_t party_id = 0; party_id < number_of_parties; ++party_id) {
    configuration.emplace_back("127.0.0.1", static_cast<std::uint16_t>(base_port + party_id));
  }

  std::vector<std::future<std::vector<std::unique_ptr<encrypto::motion::communication::Transport>>>>
      transport_futures;
  transport_futures.reserve(number_of_parties);
  for (std::size_t party_id = 0; party_id < number_of_parties; ++party_id) {
    transport_futures.emplace_back(std::async(std::launch::async, [party_id, configuration] {
      encrypto::motion::communication::TcpSetupHelper helper(party_id, configuration);
      return helper.SetupConnections();
    }));
  }

  std::vector<std::unique_ptr<encrypto::motion::Party>> parties;
  parties.reserve(number_of_parties);
  for (std::size_t party_id = 0; party_id < number_of_parties; ++party_id) {
    auto transports = transport_futures.at(party_id).get();
    auto communication_layer =
        std::make_unique<encrypto::motion::communication::CommunicationLayer>(
            party_id, std::move(transports));
    parties.emplace_back(
        std::make_unique<encrypto::motion::Party>(std::move(communication_layer)));
  }
  return parties;
}

std::vector<std::unique_ptr<encrypto::motion::Party>> MakeBenchmarkParties(
    std::size_t number_of_parties, BenchmarkTransport transport, std::uint16_t tcp_base_port) {
  switch (transport) {
    case BenchmarkTransport::kDummy:
      return encrypto::motion::MakeLocallyConnectedParties(number_of_parties, kPortOffset);
    case BenchmarkTransport::kTcp:
      return MakeTcpConnectedParties(number_of_parties, tcp_base_port);
  }
  throw std::invalid_argument("unknown benchmark transport");
}

PrimitiveGateBenchmarkResult RunPrimitiveGateBenchmark(const PrimitiveGateCase& gate_case,
                                                       std::size_t gate_count,
                                                       std::size_t number_of_parties,
                                                       BenchmarkTransport transport,
                                                       std::uint16_t tcp_base_port) {
  PrimitiveGateBenchmarkResult result;
  const auto total_start = std::chrono::steady_clock::now();

  const auto circuit_path = WritePrimitiveGateCircuit(gate_case, gate_count);
  auto cleanup_circuit = [&] {
    std::error_code ignored_error;
    std::filesystem::remove(circuit_path, ignored_error);
  };

  auto stage_start = std::chrono::steady_clock::now();
  const auto algorithm = encrypto::motion::AlgorithmDescription::FromAby(circuit_path.string());
  result.parse_ms = ToMilliseconds(std::chrono::steady_clock::now() - stage_start);

  EXPECT_EQ(algorithm.number_of_gates, gate_count);
  EXPECT_EQ(algorithm.number_of_output_wires, gate_count);

  stage_start = std::chrono::steady_clock::now();
  auto parties = MakeBenchmarkParties(number_of_parties, transport, tcp_base_port);
  for (auto& party : parties) {
    party->GetLogger()->SetEnabled(kDetailedLoggingEnabled);
    party->GetConfiguration()->SetOnlineAfterSetup(true);
  }

  const auto input = ToSingleBitInputs(gate_case.inputs);
  const std::vector<BitVector<>> dummy_input(gate_case.inputs.size(), BitVector<>(1, false));
  std::vector<encrypto::motion::ShareWrapper> outputs(number_of_parties);
  for (std::size_t party_id = 0; party_id < number_of_parties; ++party_id) {
    auto& party = parties.at(party_id);
    auto local_input = party_id == 0 ? input : dummy_input;
    encrypto::motion::ShareWrapper input_share(
        party->In<kProtocol>(std::move(local_input), 0));
    outputs.at(party_id) = input_share.Evaluate(algorithm).Out(0);
  }
  result.construct_ms = ToMilliseconds(std::chrono::steady_clock::now() - stage_start);

  std::vector<BitVector<>> opened_output;
  std::vector<std::future<void>> futures;
  futures.reserve(number_of_parties);
  stage_start = std::chrono::steady_clock::now();
  for (std::size_t party_id = 0; party_id < number_of_parties; ++party_id) {
    futures.emplace_back(std::async(std::launch::async, [party_id, &parties, &outputs,
                                                          &opened_output]() {
      auto& party = parties.at(party_id);
      party->Run();
      if (party_id == 0) {
        opened_output = outputs.at(party_id).As<std::vector<BitVector<>>>();
      }
      party->Finish();
    }));
  }
  for (auto& future : futures) {
    future.get();
  }
  result.run_ms = ToMilliseconds(std::chrono::steady_clock::now() - stage_start);

  EXPECT_EQ(opened_output.size(), gate_count);
  if (opened_output.size() != gate_count) {
    cleanup_circuit();
    return result;
  }
  for (const auto& output : opened_output) {
    EXPECT_EQ(output.Get(0), gate_case.expected_output);
  }

  for (const auto& party : parties) {
    const auto transport_statistics =
        party->GetBackend()->GetCommunicationLayer().GetTransportStatistics();
    for (const auto& peer_statistics : transport_statistics) {
      result.messages_sent += peer_statistics.number_of_messages_sent;
      result.messages_received += peer_statistics.number_of_messages_received;
      result.bytes_sent += peer_statistics.number_of_bytes_sent;
      result.bytes_received += peer_statistics.number_of_bytes_received;
    }
  }

  result.total_ms = ToMilliseconds(std::chrono::steady_clock::now() - total_start);
  cleanup_circuit();
  return result;
}

const std::vector<PrimitiveGateCase>& GetPrimitiveGateCases() {
  static const std::vector<PrimitiveGateCase> gate_cases = {
      {"XOR", 'X', {false, true}, true},
      {"AND", 'A', {false, true}, false},
      {"OR", 'V', {false, true}, true},
      {"INV", 'I', {false}, true},
      {"MUX", 'M', {false, true, true}, true},
  };
  return gate_cases;
}

void RunPrimitiveGateBenchmarkSuite(std::string_view transport_name,
                                    BenchmarkTransport transport,
                                    std::uint16_t tcp_base_port) {
  const auto gate_count = GetEnvSizeT("MOTION_FROMABY_PRIMITIVE_GATE_COUNT", 100);
  const auto number_of_parties = GetEnvSizeT("MOTION_FROMABY_PRIMITIVE_PARTIES", 2);
  ASSERT_GE(number_of_parties, 2u);

  std::cout << "FromAby primitive BooleanGMW microbenchmark: transport=" << transport_name
            << " gates_per_case=" << gate_count << " parties=" << number_of_parties << '\n';
  const auto& gate_cases = GetPrimitiveGateCases();
  for (std::size_t gate_case_i = 0; gate_case_i < gate_cases.size(); ++gate_case_i) {
    const auto& gate_case = gate_cases.at(gate_case_i);
    const auto case_tcp_base_port = static_cast<std::uint16_t>(
        tcp_base_port + gate_case_i * (number_of_parties + 1));
    const auto result = RunPrimitiveGateBenchmark(gate_case, gate_count, number_of_parties,
                                                  transport, case_tcp_base_port);
    const auto run_us_per_gate = result.run_ms * 1000.0 / static_cast<double>(gate_count);
    std::cout << "FromAby primitive gate " << gate_case.name << " transport=" << transport_name
              << ": parse_ms=" << result.parse_ms << " construct_ms=" << result.construct_ms
              << " run_ms=" << result.run_ms
              << " run_us_per_gate=" << run_us_per_gate << " messages_sent="
              << result.messages_sent << " bytes_sent=" << result.bytes_sent
              << " messages_received=" << result.messages_received << " bytes_received="
              << result.bytes_received << " total_ms=" << result.total_ms << '\n';
  }
}

TEST(FromAbyPrimitivePerformance, BooleanGmwPrimitiveGates) {
  RunPrimitiveGateBenchmarkSuite("dummy", BenchmarkTransport::kDummy, 0);
}

TEST(FromAbyPrimitivePerformance, DISABLED_BooleanGmwPrimitiveGatesTcp) {
  const auto number_of_parties = GetEnvSizeT("MOTION_FROMABY_PRIMITIVE_PARTIES", 2);
  const auto base_port = GetEnvSizeT("MOTION_FROMABY_PRIMITIVE_TCP_BASE_PORT", 24000);
  const auto port_span = GetPrimitiveGateCases().size() * (number_of_parties + 1);
  ASSERT_LE(base_port + port_span, std::numeric_limits<std::uint16_t>::max());
  RunPrimitiveGateBenchmarkSuite("tcp", BenchmarkTransport::kTcp,
                                 static_cast<std::uint16_t>(base_port));
}

}  // namespace
